modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_github}"
    logoFile="${mod_logo}"
    #credits=""
    authors="${mod_authors}"
    description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"
${integration_mixin_blocks}

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

#[modproperties.${mod_id}]

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_dragons_plus"
    type="required"
    versionRange="${create_dragons_plus_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="optional"
    versionRange="${farmers_delight_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="culturaldelights"
    type="optional"
    versionRange="${cultural_delights_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cookscollection"
    type="optional"
    versionRange="${cooks_collection_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="endersdelight"
    type="optional"
    versionRange="${enders_delight_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="upgrade_aquatic"
    type="optional"
    versionRange="${upgrade_aquatic_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="netherdepthsupgrade"
    type="optional"
    versionRange="${nether_depths_upgrade_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neapolitan"
    type="optional"
    versionRange="${neapolitan_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="atmospheric"
    type="optional"
    versionRange="${atmospheric_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="supplementaries"
    type="optional"
    versionRange="${supplementaries_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="hauntedharvest"
    type="optional"
    versionRange="${haunted_harvest_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="netherexp"
    type="optional"
    versionRange="${nether_expansion_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tide"
    type="optional"
    versionRange="${tide_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="starcatcher"
    type="optional"
    versionRange="${starcatcher_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="confluence"
    type="optional"
    versionRange="${confluence_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="vanillabackport"
    type="optional"
    versionRange="${vanilla_backport_version_range}"
    ordering="AFTER"
    side="BOTH"
